services:
  web:
    image: 'nginx:1.23.4-alpine'
    ports:
      - '8080:80'
    volumes:
      - './:/var/www/html'
      - './docker/nginx:/etc/nginx/conf.d'
    depends_on:
      - php
      - mongodb

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './:/var/www/html'

  mongodb:
    image: mongo:6.0
    restart: always 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb_data:/data/db'
      - './docker/mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro'

volumes:
  mongodb_data:
    name: dashboard_mongodb_data